apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: course
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: 108356037/flask-ping-pong
    context: ping_pong
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - skaffold_yamls/flask-ping-pong-pod.yaml
    - skaffold_yamls/flask-ping-pong-deployment.yaml
    - skaffold_yamls/flask-ping-pong-srv.yaml