apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx-depl
spec:
  # 你需要的pod數量
  replicas: 2

  # selector是replicaset用來尋找符合需求的pod，
  # 下面template的pod label中必須有符合的label 
  selector:
    matchLabels:
      app: ngx-depl

  # template是你透過replicaset想要生成的pod
  # 實際上就是pod的yaml但少了kind/apiversion
  template:
    metadata:
      labels:
        app: ngx-depl
    spec:
      containers:
      - image: nginx
        name: nginx